---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirisha
spec:
  replicas: 5
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/cycle
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: saikrishna
spec:
  type: LoadBalancer
  selector:
    app: uber
  ports:
    - port: 80
      targetPort: 80
      
